name: dart_concurrency2
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  rxdart: ^0.27.2
  #  path: ^1.7.0
  bloc: ^7.2.1

dev_dependencies:
  pedantic: ^1.9.0